#!/usr/bin/env bash
set -euo pipefail
readonly HEADLESS="HEADLESS-1"

readonly ACTION="$1"
if [[ "$ACTION" != "on" ]] && [[ "$ACTION" != "off" ]]; then
   echo "Error: on or off argument required" >&2
   exit 1
fi

wlr-randr --output "$HEADLESS" "--${ACTION}"

if [[ "$ACTION" == "on" ]]; then
  sudo systemctl restart lightdm
fi
